# site settings
title: ykaseng
subtitle: Ka Seng Yang
email: kaseng.y@gmail.com
name: ykaseng
description: Learn more about me and my work here!
url: "http://ykaseng.com" # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog
author:
street_address:
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/ykaseng
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ykaseng
rss_url: http://ykaseng.com/feed.xml

# build settings
markdown: kramdown

sass:
  style: compressed
